# Generated by Django 4.2.4 on 2023-08-19 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_company_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_no', models.PositiveSmallIntegerField(default=0)),
                ('sales_value', models.FloatField(default=0)),
                ('purchases_no', models.PositiveSmallIntegerField(default=0)),
                ('purchases_value', models.FloatField(default=0)),
                ('offers_no', models.PositiveSmallIntegerField(default=0)),
                ('offers_value', models.FloatField(default=0)),
                ('payments_no', models.PositiveSmallIntegerField(default=0)),
                ('payments_value', models.FloatField(default=0)),
                ('receipts_no', models.PositiveSmallIntegerField(default=0)),
                ('receipts_value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.details')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
