# Generated by Django 4.2.4 on 2023-08-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_details_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='offers_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='payments_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='purchases_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='receipts_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='sales_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
