# Generated by Django 4.2.4 on 2023-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_details_offers_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='offers_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='payments_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='purchases_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='receipts_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='sales_value',
            field=models.FloatField(default=0),
        ),
    ]
