# Generated by Django 4.2.4 on 2023-09-04 13:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='images'),
        ),
    ]
