# Generated by Django 4.2.4 on 2023-09-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_gov_city_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
