# Generated by Django 4.2.4 on 2023-12-21 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='members.address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
