# Generated by Django 4.2.4 on 2023-12-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_alter_tenderrequest_created_at_tenderoffer_offeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='re_of',
            field=models.IntegerField(choices=[(1, 'طلب'), (2, 'عرض')], default=1),
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='tenders.tenderoffer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='tenders.question')),
            ],
        ),
    ]
