# Generated by Django 4.2.4 on 2023-09-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpoffers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpoffer',
            name='submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pumpoffer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
