# Generated by Django 4.2.4 on 2023-09-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpoffers', '0002_pumpoffer_submit_alter_pumpoffer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpoffer',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
