# Generated by Django 4.2.4 on 2023-10-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pumpoffers', '0005_irrigation_powersource_pumpofferrequest_irrigation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=55)),
                ('days', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pumpoffer',
            name='include_taxes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pumpoffer',
            name='include_trans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pumpoffer',
            name='installment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pumpoffer',
            name='valid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pumpoffers.validity'),
        ),
    ]
