# Generated by Django 4.2.4 on 2023-11-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_image'),
        ('pumpoffers', '0006_validity_pumpoffer_include_taxes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='offerCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('offer_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='pumpoffers.offersapp')),
            ],
        ),
        migrations.AddField(
            model_name='pumpofferrequest',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='pumpoffers.offersapp'),
        ),
    ]
