# Generated by Django 4.2.4 on 2023-08-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_cartitem_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='q',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='credit',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='depit',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='value',
            field=models.FloatField(),
        ),
    ]
