# Generated by Django 4.2.4 on 2023-08-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_cartitem_q_alter_credit_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
