# Generated by Django 4.2.4 on 2023-08-17 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitestats', '0001_initial'),
        ('accounting', '0009_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sitestats.site'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sitestats.site'),
        ),
    ]
