# Generated by Django 4.2.4 on 2023-08-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_remove_offer_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='value',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='value',
        ),
    ]
