# Generated by Django 4.2.4 on 2023-09-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20230907_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='member',
            new_name='user',
        )
    ]
