# Generated by Django 4.2.4 on 2023-08-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bool_spec', to='products.product')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bool_spec', to='products.spec')),
            ],
        ),
        migrations.CreateModel(
            name='NumSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_spec', to='products.product')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_spec', to='products.spec')),
            ],
        ),
        migrations.CreateModel(
            name='TxtSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txt_spec', to='products.product')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txt_spec', to='products.spec')),
            ],
        ),
        migrations.DeleteModel(
            name='SpecValue',
        ),
    ]
