# Generated by Django 4.2.4 on 2023-08-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_boolspecs_numspecs_txtspecs_delete_specvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='boolspecs',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='numspecs',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='txtspecs',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
