# Generated by Django 4.2.4 on 2023-08-17 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitestats', '0001_initial'),
        ('products', '0003_boolspecs_order_numspecs_order_txtspecs_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sitestats.site'),
        ),
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sitestats.site'),
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sitestats.site'),
        ),
    ]
