# Generated by Django 4.2.4 on 2023-08-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='purchases',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
