# Generated by Django 5.0 on 2023-12-29 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='name',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='spec',
            name='type',
            field=models.IntegerField(choices=[(1, 'رقمي'), (2, 'نصي'), (3, 'نعم او لا')]),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=55)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='products.spec')),
            ],
        ),
        migrations.CreateModel(
            name='SpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.product')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.spec')),
            ],
        ),
    ]
