# Generated by Django 4.2.4 on 2023-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.PositiveIntegerField(default=0)),
                ('companies', models.PositiveIntegerField(default=0)),
                ('categories', models.PositiveIntegerField(default=0)),
                ('products', models.PositiveIntegerField(default=0)),
                ('brands', models.PositiveIntegerField(default=0)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('offers', models.PositiveIntegerField(default=0)),
                ('pageview', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
