# Generated by Django 4.2.4 on 2023-09-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitestats', '0002_site_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('privacy', models.TextField()),
                ('return_policy', models.TextField()),
            ],
        ),
    ]
