# Generated by Django 4.2.4 on 2023-09-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitestats', '0003_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='static',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='static',
            name='mission',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='static',
            name='privacy',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='static',
            name='return_policy',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='static',
            name='vision',
            field=models.TextField(null=True),
        ),
    ]
